Awswordpress
jhash1/awswordpress pull request #6
Opened 2022-08-15 18:30 UTC by jhash1

2022-08-15 18:39 UTC, vladimirmukhin requested changes
Please do the following:
- Rename this pull request. We need the name that describes what exactly changed. For example "Configure a VPC"
- Remove db.tf this code is not relevant to this task. It's a bad practice to mix multiple irrelevant changes in a single PR

2022-08-15 19:37 UTC, vladimirmukhin requested changes

2022-08-15 19:37 UTC, vladimirmukhin commented on variables.tf
> +# }
Please don't leave commented-out code blocks. It's a bad style practice

2022-08-15 19:37 UTC, vladimirmukhin commented on variables.tf
> +variable "public_cidr" {}
Please always add an empty newline to the end of file.
Linux tools and systems expect a newline at the end of file and might work not correctly

2022-08-15 19:38 UTC, vladimirmukhin requested changes
Not all resources are tagged. Please check your code and add missing tags

2022-08-15 20:35 UTC, jhash1 commented on variables.tf
> +variable "public_cidr" {}
all set

2022-08-16 16:03 UTC, vladimirmukhin approved these changes

2022-08-16 16:35 UTC, merged